// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NihongoLms.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NihongoLms.Infrastructure.Migrations
{
    [DbContext(typeof(LmsDbContext))]
    [Migration("20260815175855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NihongoLms.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("JlptLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JlptLevel");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.DriveNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DriveCreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DriveModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeletedInDrive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<string>("ParentDriveFileId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailLink")
                        .HasColumnType("text");

                    b.Property<string>("WebViewLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriveFileId")
                        .IsUnique();

                    b.HasIndex("ParentDriveFileId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("RawPath");

                    b.ToTable("DriveNodes");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuizPassed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("PassPercentage")
                        .HasColumnType("integer");

                    b.Property<int>("QuizType")
                        .HasColumnType("integer");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxScore")
                        .HasColumnType("double precision");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "QuizId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioDriveNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageDriveNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AudioDriveNodeId");

                    b.HasIndex("ImageDriveNodeId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomUrl")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DriveNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriveNodeId");

                    b.HasIndex("LessonId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.ReviewSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("IntervalDays")
                        .HasColumnType("double precision");

                    b.Property<int?>("LastQuality")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.HasIndex("UserId", "NextReviewDateUtc");

                    b.ToTable("ReviewSchedules");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.SrsReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EaseFactorAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("EaseFactorBefore")
                        .HasColumnType("double precision");

                    b.Property<double>("IntervalAfterDays")
                        .HasColumnType("double precision");

                    b.Property<double>("IntervalBeforeDays")
                        .HasColumnType("double precision");

                    b.Property<int>("QualityRating")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SrsReviewLogs");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.UserOAuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserOAuthTokens");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioDriveNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSentenceTranslation")
                        .HasColumnType("text");

                    b.Property<string>("JlptLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StrokeOrderDriveNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AudioDriveNodeId");

                    b.HasIndex("JlptLevel");

                    b.HasIndex("LessonId");

                    b.HasIndex("StrokeOrderDriveNodeId");

                    b.HasIndex("Word");

                    b.ToTable("VocabularyEntries");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.DriveNode", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "AudioDriveNode")
                        .WithMany()
                        .HasForeignKey("AudioDriveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "ImageDriveNode")
                        .WithMany()
                        .HasForeignKey("ImageDriveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NihongoLms.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioDriveNode");

                    b.Navigation("ImageDriveNode");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Resource", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "DriveNode")
                        .WithMany("LinkedResources")
                        .HasForeignKey("DriveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NihongoLms.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Resources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriveNode");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.ReviewSchedule", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("ReviewSchedules")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Section", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "AudioDriveNode")
                        .WithMany()
                        .HasForeignKey("AudioDriveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NihongoLms.Domain.Entities.Lesson", "Lesson")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NihongoLms.Domain.Entities.DriveNode", "StrokeOrderDriveNode")
                        .WithMany()
                        .HasForeignKey("StrokeOrderDriveNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AudioDriveNode");

                    b.Navigation("Lesson");

                    b.Navigation("StrokeOrderDriveNode");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.DriveNode", b =>
                {
                    b.Navigation("ChildNodes");

                    b.Navigation("LinkedResources");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("ProgressRecords");

                    b.Navigation("Quizzes");

                    b.Navigation("Resources");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.Section", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("NihongoLms.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("ReviewSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
