export interface KanjiExample {
  word: string;
  reading: string;
  meaning: string;
}

export interface KanjiItem {
  id: string;
  character: string;
  hanViet: string;
  meaning: string;
  onyomi: string[];
  kunyomi: string[];
  strokeCount: number;
  jlpt: "N5" | "N4" | "N3" | "N2" | "N1";
  radical: string;
  radicalName: string;
  examples: KanjiExample[];
}

export interface RadicalGroup {
  radical: string;
  name: string;
  meaning: string;
  strokeCount: number;
}

export const RADICALS_LIST: RadicalGroup[] = [
  { radical: "一", name: "Nhất", meaning: "Số một", strokeCount: 1 },
  { radical: "人", name: "Nhân (亻)", meaning: "Con người", strokeCount: 2 },
  { radical: "口", name: "Khẩu", meaning: "Cái miệng", strokeCount: 3 },
  { radical: "土", name: "Thổ", meaning: "Đất đá", strokeCount: 3 },
  { radical: "女", name: "Nữ", meaning: "Phụ nữ", strokeCount: 3 },
  { radical: "子", name: "Tử", meaning: "Con cái", strokeCount: 3 },
  { radical: "山", name: "Sơn", meaning: "Núi non", strokeCount: 3 },
  { radical: "日", name: "Nhật", meaning: "Mặt trời, ngày", strokeCount: 4 },
  { radical: "月", name: "Nguyệt", meaning: "Mặt trăng, tháng", strokeCount: 4 },
  { radical: "木", name: "Mộc", meaning: "Cây cối", strokeCount: 4 },
  { radical: "水", name: "Thủy (氵)", meaning: "Nước", strokeCount: 4 },
  { radical: "火", name: "Hỏa (灬)", meaning: "Lửa", strokeCount: 4 },
  { radical: "田", name: "Điền", meaning: "Ruộng đồng", strokeCount: 5 },
  { radical: "目", name: "Mục", meaning: "Mắt", strokeCount: 5 },
  { radical: "心", name: "Tâm (忄)", meaning: "Trái tim, tâm trí", strokeCount: 4 },
  { radical: "言", name: "Ngôn (訁)", meaning: "Lời nói", strokeCount: 7 },
  { radical: "金", name: "Kim (釒)", meaning: "Kim loại, vàng, tiền", strokeCount: 8 },
  { radical: "車", name: "Xa", meaning: "Xe cộ", strokeCount: 7 },
  { radical: "門", name: "Môn", meaning: "Cánh cổng", strokeCount: 8 },
  { radical: "雨", name: "Vũ", meaning: "Mưa gió", strokeCount: 8 },
  { radical: "食", name: "Thực (飠)", meaning: "Ăn uống, thức ăn", strokeCount: 9 },
];

export const KANJI_DATABASE: KanjiItem[] = [
  // ─── JLPT N5 ─────────────────────────────────────────────────────────────
  {
    id: "n5-nichi",
    character: "日",
    hanViet: "NHẬT",
    meaning: "Mặt trời, ngày, Nhật Bản",
    onyomi: ["ニチ", "ジツ"],
    kunyomi: ["ひ", "-び", "-か"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "日",
    radicalName: "Bộ Nhật",
    examples: [
      { word: "日本", reading: "にほん (Nihon)", meaning: "Nước Nhật Bản" },
      { word: "日曜日", reading: "にちようび (Nichiyoubi)", meaning: "Chủ nhật" },
      { word: "毎日", reading: "まいにち (Mainichi)", meaning: "Mỗi ngày" },
      { word: "休日", reading: "きゅうじつ (Kyuujitsu)", meaning: "Ngày nghỉ" },
    ],
  },
  {
    id: "n5-hon",
    character: "本",
    hanViet: "BẢN / BỔN",
    meaning: "Sách, gốc rễ, nguồn gốc",
    onyomi: ["ホン"],
    kunyomi: ["もと"],
    strokeCount: 5,
    jlpt: "N5",
    radical: "木",
    radicalName: "Bộ Mộc",
    examples: [
      { word: "本", reading: "ほん (Hon)", meaning: "Quyển sách" },
      { word: "日本", reading: "にほん (Nihon)", meaning: "Nhật Bản" },
      { word: "本当", reading: "ほんとう (Hontou)", meaning: "Sự thật, thật sự" },
      { word: "山本", reading: "やまもと (Yamamoto)", meaning: "Họ Yamamoto" },
    ],
  },
  {
    id: "n5-jin",
    character: "人",
    hanViet: "NHÂN",
    meaning: "Người, nhân loại",
    onyomi: ["ジン", "ニン"],
    kunyomi: ["ひと"],
    strokeCount: 2,
    jlpt: "N5",
    radical: "人",
    radicalName: "Bộ Nhân",
    examples: [
      { word: "日本人", reading: "にほんじん (Nihonjin)", meaning: "Người Nhật" },
      { word: "一人", reading: "ひとり (Hitori)", meaning: "Một người" },
      { word: "三人", reading: "さんにん (Sannin)", meaning: "Ba người" },
      { word: "大人", reading: "おとな (Otona)", meaning: "Người lớn" },
    ],
  },
  {
    id: "n5-tsuki",
    character: "月",
    hanViet: "NGUYỆT",
    meaning: "Mặt trăng, tháng",
    onyomi: ["ゲツ", "ガツ"],
    kunyomi: ["つき"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "月",
    radicalName: "Bộ Nguyệt",
    examples: [
      { word: "月曜日", reading: "げつようび (Getsuyoubi)", meaning: "Thứ hai" },
      { word: "一月", reading: "いちがつ (Ichigatsu)", meaning: "Tháng một" },
      { word: "今月", reading: "こんげつ (Kongetsu)", meaning: "Tháng này" },
      { word: "毎月", reading: "まいつき (Maitsuki)", meaning: "Hàng tháng" },
    ],
  },
  {
    id: "n5-hi",
    character: "火",
    hanViet: "HỎA",
    meaning: "Lửa, hỏa hoạn",
    onyomi: ["カ"],
    kunyomi: ["ひ", "-び", "ほ-"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "火",
    radicalName: "Bộ Hỏa",
    examples: [
      { word: "火曜日", reading: "かようび (Kayoubi)", meaning: "Thứ ba" },
      { word: "火事", reading: "かじ (Kaji)", meaning: "Hỏa hoạn, vụ cháy" },
      { word: "花火", reading: "はなび (Hanabi)", meaning: "Pháo hoa" },
    ],
  },
  {
    id: "n5-mizu",
    character: "水",
    hanViet: "THỦY",
    meaning: "Nước",
    onyomi: ["スイ"],
    kunyomi: ["みず"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "水",
    radicalName: "Bộ Thủy",
    examples: [
      { word: "水曜日", reading: "すいようび (Suiyoubi)", meaning: "Thứ tư" },
      { word: "水", reading: "みず (Mizu)", meaning: "Nước uống" },
      { word: "水泳", reading: "すいえい (Suiei)", meaning: "Bơi lội" },
      { word: "冷水", reading: "れいすい (Reisui)", meaning: "Nước lạnh" },
    ],
  },
  {
    id: "n5-ki",
    character: "木",
    hanViet: "MỘC",
    meaning: "Cây, gỗ",
    onyomi: ["ボク", "モク"],
    kunyomi: ["き", "こ-"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "木",
    radicalName: "Bộ Mộc",
    examples: [
      { word: "木曜日", reading: "もくようび (Mokuyoubi)", meaning: "Thứ năm" },
      { word: "木", reading: "き (Ki)", meaning: "Cây cối" },
      { word: "木造", reading: "もくぞう (Mokuzou)", meaning: "Làm bằng gỗ" },
    ],
  },
  {
    id: "n5-kin",
    character: "金",
    hanViet: "KIM",
    meaning: "Vàng, tiền, kim loại",
    onyomi: ["キン", "コン"],
    kunyomi: ["かね", "かな-"],
    strokeCount: 8,
    jlpt: "N5",
    radical: "金",
    radicalName: "Bộ Kim",
    examples: [
      { word: "金曜日", reading: "きんようび (Kinyoubi)", meaning: "Thứ sáu" },
      { word: "お金", reading: "おかね (Okane)", meaning: "Tiền bạc" },
      { word: "料金", reading: "りょうきん (Ryoukin)", meaning: "Phí tổn, cước phí" },
      { word: "現金", reading: "げんきん (Genkin)", meaning: "Tiền mặt" },
    ],
  },
  {
    id: "n5-tsuchi",
    character: "土",
    hanViet: "THỔ",
    meaning: "Đất, bùn đất",
    onyomi: ["ド", "ト"],
    kunyomi: ["つち"],
    strokeCount: 3,
    jlpt: "N5",
    radical: "土",
    radicalName: "Bộ Thổ",
    examples: [
      { word: "土曜日", reading: "どようび (Doyoubi)", meaning: "Thứ bảy" },
      { word: "土地", reading: "とち (Tochi)", meaning: "Đất đai" },
      { word: "お土産", reading: "おみやげ (Omiyage)", meaning: "Quà lưu niệm" },
    ],
  },
  {
    id: "n5-yama",
    character: "山",
    hanViet: "SƠN / SAN",
    meaning: "Núi non",
    onyomi: ["サン", "セン"],
    kunyomi: ["やま"],
    strokeCount: 3,
    jlpt: "N5",
    radical: "山",
    radicalName: "Bộ Sơn",
    examples: [
      { word: "富士山", reading: "ふじさん (Fujisan)", meaning: "Núi Phú Sĩ" },
      { word: "山", reading: "やま (Yama)", meaning: "Ngọn núi" },
      { word: "登山", reading: "とざん (Tozan)", meaning: "Leo núi" },
    ],
  },
  {
    id: "n5-kawa",
    character: "川",
    hanViet: "XUYÊN",
    meaning: "Sông suối",
    onyomi: ["セン"],
    kunyomi: ["かわ"],
    strokeCount: 3,
    jlpt: "N5",
    radical: "川",
    radicalName: "Bộ Xuyên",
    examples: [
      { word: "川", reading: "かわ (Kawa)", meaning: "Dòng sông" },
      { word: "小川", reading: "おがわ (Ogawa)", meaning: "Dòng suối nhỏ" },
      { word: "河川", reading: "かせん (Kasen)", meaning: "Sông ngòi" },
    ],
  },
  {
    id: "n5-ta",
    character: "田",
    hanViet: "ĐIỀN",
    meaning: "Ruộng đồng",
    onyomi: ["デン"],
    kunyomi: ["た"],
    strokeCount: 5,
    jlpt: "N5",
    radical: "田",
    radicalName: "Bộ Điền",
    examples: [
      { word: "田んぼ", reading: "たんぼ (Tanbo)", meaning: "Ruộng lúa" },
      { word: "田中", reading: "たなか (Tanaka)", meaning: "Họ Tanaka" },
      { word: "水田", reading: "すいでん (Suiden)", meaning: "Ruộng nước" },
    ],
  },
  {
    id: "n5-dai",
    character: "大",
    hanViet: "ĐẠI",
    meaning: "To, lớn, vĩ đại",
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["おお-", "おお.きい", "おお.いに"],
    strokeCount: 3,
    jlpt: "N5",
    radical: "大",
    radicalName: "Bộ Đại",
    examples: [
      { word: "大きい", reading: "おおきい (Ookii)", meaning: "To lớn" },
      { word: "大学", reading: "だいがく (Daigaku)", meaning: "Trường đại học" },
      { word: "大変", reading: "たいへん (Taihen)", meaning: "Vất vả, ghê gớm" },
      { word: "大人", reading: "おとな (Otona)", meaning: "Người lớn" },
    ],
  },
  {
    id: "n5-shou",
    character: "小",
    hanViet: "TIỂU",
    meaning: "Nhỏ, bé, ít ỏi",
    onyomi: ["ショウ"],
    kunyomi: ["ちい.さい", "こ-", "お-"],
    strokeCount: 3,
    jlpt: "N5",
    radical: "小",
    radicalName: "Bộ Tiểu",
    examples: [
      { word: "小さい", reading: "ちいさい (Chiisai)", meaning: "Nhỏ bé" },
      { word: "小学校", reading: "しょうがっこう (Shougakkou)", meaning: "Trường tiểu học" },
      { word: "小説", reading: "しょうせつ (Shousetsu)", meaning: "Tiểu thuyết" },
    ],
  },
  {
    id: "n5-gaku",
    character: "学",
    hanViet: "HỌC",
    meaning: "Học tập, trường học",
    onyomi: ["ガク"],
    kunyomi: ["まな.ぶ"],
    strokeCount: 8,
    jlpt: "N5",
    radical: "子",
    radicalName: "Bộ Tử",
    examples: [
      { word: "学校", reading: "がっこう (Gakkou)", meaning: "Trường học" },
      { word: "学生", reading: "がくせい (Gakusei)", meaning: "Học sinh, sinh viên" },
      { word: "学ぶ", reading: "まなぶ (Manabu)", meaning: "Học hỏi" },
      { word: "留学生", reading: "りゅうがくせい (Ryuugakusei)", meaning: "Du học sinh" },
    ],
  },
  {
    id: "n5-sei",
    character: "生",
    hanViet: "SINH",
    meaning: "Sống, sinh sôi, sinh viên",
    onyomi: ["セイ", "ショウ"],
    kunyomi: ["い.きる", "う.まれる", "なま"],
    strokeCount: 5,
    jlpt: "N5",
    radical: "生",
    radicalName: "Bộ Sinh",
    examples: [
      { word: "先生", reading: "せんせい (Sensei)", meaning: "Thầy cô giáo" },
      { word: "学生", reading: "がくせい (Gakusei)", meaning: "Học sinh" },
      { word: "生きる", reading: "いきる (Ikiru)", meaning: "Sống" },
      { word: "生まれる", reading: "うまれる (Umareru)", meaning: "Được sinh ra" },
    ],
  },
  {
    id: "n5-sen",
    character: "先",
    hanViet: "TIÊN",
    meaning: "Trước, tiên tiến, tương lai",
    onyomi: ["セン"],
    kunyomi: ["さき", "ま.ず"],
    strokeCount: 6,
    jlpt: "N5",
    radical: "儿",
    radicalName: "Bộ Nhi",
    examples: [
      { word: "先生", reading: "せんせい (Sensei)", meaning: "Thầy giáo" },
      { word: "先週", reading: "せんしゅう (Senshuu)", meaning: "Tuần trước" },
      { word: "先月", reading: "せんげつ (Sengetsu)", meaning: "Tháng trước" },
      { word: "お先に", reading: "おさきに (Osakini)", meaning: "Tôi xin phép trước" },
    ],
  },
  {
    id: "n5-watashi",
    character: "私",
    hanViet: "TƯ",
    meaning: "Tôi, cá nhân, riêng tư",
    onyomi: ["シ"],
    kunyomi: ["わたし", "わたくし"],
    strokeCount: 7,
    jlpt: "N5",
    radical: "禾",
    radicalName: "Bộ Hòa",
    examples: [
      { word: "私", reading: "わたし (Watashi)", meaning: "Tôi" },
      { word: "私たち", reading: "わたしたち (Watashitachi)", meaning: "Chúng tôi, chúng ta" },
      { word: "私立", reading: "しりつ (Shiritsu)", meaning: "Dân lập, tư nhân" },
    ],
  },
  {
    id: "n5-kuni",
    character: "国",
    hanViet: "QUỐC",
    meaning: "Đất nước, quốc gia",
    onyomi: ["コク"],
    kunyomi: ["くに"],
    strokeCount: 8,
    jlpt: "N5",
    radical: "囗",
    radicalName: "Bộ Vi",
    examples: [
      { word: "外国", reading: "がいこく (Gaikoku)", meaning: "Nước ngoài" },
      { word: "国", reading: "くに (Kuni)", meaning: "Đất nước" },
      { word: "中国", reading: "ちゅうごく (Chuugoku)", meaning: "Trung Quốc" },
      { word: "国際", reading: "こくさい (Kokusai)", meaning: "Quốc tế" },
    ],
  },
  {
    id: "n5-go",
    character: "語",
    hanViet: "NGỮ",
    meaning: "Ngôn ngữ, từ ngữ",
    onyomi: ["ゴ"],
    kunyomi: ["かた.る", "かた.らう"],
    strokeCount: 14,
    jlpt: "N5",
    radical: "言",
    radicalName: "Bộ Ngôn",
    examples: [
      { word: "日本語", reading: "にほんご (Nihongo)", meaning: "Tiếng Nhật" },
      { word: "英語", reading: "えいご (Eigo)", meaning: "Tiếng Anh" },
      { word: "単語", reading: "たんご (Tango)", meaning: "Từ vựng" },
      { word: "語学", reading: "ごがく (Gogaku)", meaning: "Học ngôn ngữ" },
    ],
  },
  {
    id: "n5-kou",
    character: "校",
    hanViet: "HIỆU",
    meaning: "Trường học, chỉnh lý",
    onyomi: ["コウ"],
    kunyomi: [],
    strokeCount: 10,
    jlpt: "N5",
    radical: "木",
    radicalName: "Bộ Mộc",
    examples: [
      { word: "学校", reading: "がっこう (Gakkou)", meaning: "Trường học" },
      { word: "高校", reading: "こうこう (Koukou)", meaning: "Trường cấp 3" },
      { word: "校長", reading: "こうちょう (Kouchou)", meaning: "Hiệu trưởng" },
    ],
  },
  {
    id: "n5-ima",
    character: "今",
    hanViet: "KIM",
    meaning: "Bây giờ, hiện tại",
    onyomi: ["コン", "キン"],
    kunyomi: ["いま"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "人",
    radicalName: "Bộ Nhân",
    examples: [
      { word: "今", reading: "いま (Ima)", meaning: "Bây giờ" },
      { word: "今日", reading: "きょう (Kyou)", meaning: "Hôm nay" },
      { word: "今年", reading: "ことし (Kotoshi)", meaning: "Năm nay" },
      { word: "今晩", reading: "こんばん (Konban)", meaning: "Tối nay" },
    ],
  },
  {
    id: "n5-nani",
    character: "何",
    hanViet: "HÀ",
    meaning: "Cái gì, bao nhiêu",
    onyomi: ["カ"],
    kunyomi: ["なに", "なん"],
    strokeCount: 7,
    jlpt: "N5",
    radical: "人",
    radicalName: "Bộ Nhân",
    examples: [
      { word: "何", reading: "なに / なん (Nani / Nan)", meaning: "Cái gì" },
      { word: "何時", reading: "なんじ (Nanji)", meaning: "Mấy giờ" },
      { word: "何人", reading: "なんにん (Nannin)", meaning: "Mấy người" },
    ],
  },
  {
    id: "n5-taberu",
    character: "食",
    hanViet: "THỰC",
    meaning: "Ăn, ẩm thực",
    onyomi: ["ショク", "ジキ"],
    kunyomi: ["た.べる", "く.う"],
    strokeCount: 9,
    jlpt: "N5",
    radical: "食",
    radicalName: "Bộ Thực",
    examples: [
      { word: "食べる", reading: "たべる (Taberu)", meaning: "Ăn" },
      { word: "食事", reading: "しょくじ (Shokuji)", meaning: "Bữa ăn" },
      { word: "食堂", reading: "しょくどう (Shokudou)", meaning: "Nhà ăn, căng tin" },
      { word: "朝食", reading: "ちょうしょく (Choushoku)", meaning: "Bữa sáng" },
    ],
  },
  {
    id: "n5-nomu",
    character: "飲",
    hanViet: "ẨM",
    meaning: "Uống, ẩm thực",
    onyomi: ["イン"],
    kunyomi: ["の.む"],
    strokeCount: 12,
    jlpt: "N5",
    radical: "食",
    radicalName: "Bộ Thực",
    examples: [
      { word: "飲む", reading: "のむ (Nomu)", meaning: "Uống" },
      { word: "飲み物", reading: "のみもの (Nomimono)", meaning: "Đồ uống" },
      { word: "飲食店", reading: "いんしょくてん (Inshokuten)", meaning: "Quán ăn" },
    ],
  },
  {
    id: "n5-miru",
    character: "見",
    hanViet: "KIẾN",
    meaning: "Nhìn, xem, ý kiến",
    onyomi: ["ケン"],
    kunyomi: ["み.る", "み.える", "み.せる"],
    strokeCount: 7,
    jlpt: "N5",
    radical: "見",
    radicalName: "Bộ Kiến",
    examples: [
      { word: "見る", reading: "みる (Miru)", meaning: "Xem, nhìn" },
      { word: "見せる", reading: "みせる (Miseru)", meaning: "Cho xem" },
      { word: "意見", reading: "いけん (Iken)", meaning: "Ý kiến" },
      { word: "見学", reading: "けんがく (Kengaku)", meaning: "Tham quan học tập" },
    ],
  },
  {
    id: "n5-kiku",
    character: "聞",
    hanViet: "VĂN / VẤN",
    meaning: "Nghe, hỏi, tin tức",
    onyomi: ["ブン", "モン"],
    kunyomi: ["き.く", "き.こえる"],
    strokeCount: 14,
    jlpt: "N5",
    radical: "門",
    radicalName: "Bộ Môn",
    examples: [
      { word: "聞く", reading: "きく (Kiku)", meaning: "Nghe, hỏi" },
      { word: "新聞", reading: "しんぶん (Shinbun)", meaning: "Tờ báo" },
      { word: "聞こえる", reading: "きこえる (Kikoeru)", meaning: "Nghe thấy" },
    ],
  },
  {
    id: "n5-yomu",
    character: "読",
    hanViet: "ĐỘC",
    meaning: "Đọc sách, tụng đọc",
    onyomi: ["ドク", "トク"],
    kunyomi: ["よ.む"],
    strokeCount: 14,
    jlpt: "N5",
    radical: "言",
    radicalName: "Bộ Ngôn",
    examples: [
      { word: "読む", reading: "よむ (Yomu)", meaning: "Đọc" },
      { word: "読書", reading: "どくしょ (Dokusho)", meaning: "Đọc sách" },
      { word: "読解", reading: "どっかい (Dokkai)", meaning: "Đọc hiểu" },
    ],
  },
  {
    id: "n5-kaku",
    character: "書",
    hanViet: "THƯ",
    meaning: "Viết, sách vở, thư từ",
    onyomi: ["ショ"],
    kunyomi: ["か.く"],
    strokeCount: 10,
    jlpt: "N5",
    radical: "曰",
    radicalName: "Bộ Viết",
    examples: [
      { word: "書く", reading: "かく (Kaku)", meaning: "Viết" },
      { word: "図書館", reading: "としょかん (Toshokan)", meaning: "Thư viện" },
      { word: "教科書", reading: "きょうかしょ (Kyoukasho)", meaning: "Sách giáo khoa" },
      { word: "辞書", reading: "じしょ (Jisho)", meaning: "Từ điển" },
    ],
  },
  {
    id: "n5-hanasu",
    character: "話",
    hanViet: "THOẠI",
    meaning: "Nói chuyện, câu chuyện, đàm thoại",
    onyomi: ["ワ"],
    kunyomi: ["はな.す", "はなし"],
    strokeCount: 13,
    jlpt: "N5",
    radical: "言",
    radicalName: "Bộ Ngôn",
    examples: [
      { word: "話す", reading: "はなす (Hanasu)", meaning: "Nói chuyện" },
      { word: "話", reading: "はなし (Hanashi)", meaning: "Câu chuyện" },
      { word: "電話", reading: "でんわ (Denwa)", meaning: "Điện thoại" },
      { word: "会話", reading: "かいわ (Kaiwa)", meaning: "Hội thoại" },
    ],
  },
  {
    id: "n5-iku",
    character: "行",
    hanViet: "HÀNH / HÀNG",
    meaning: "Đi, thực hiện, ngân hàng",
    onyomi: ["コウ", "ギョウ"],
    kunyomi: ["い.く", "ゆ.く", "おこな.う"],
    strokeCount: 6,
    jlpt: "N5",
    radical: "行",
    radicalName: "Bộ Hành",
    examples: [
      { word: "行く", reading: "いく (Iku)", meaning: "Đi" },
      { word: "銀行", reading: "ぎんこう (Ginkou)", meaning: "Ngân hàng" },
      { word: "旅行", reading: "りょこう (Ryokou)", meaning: "Du lịch" },
      { word: "行う", reading: "おこなう (Okonau)", meaning: "Tiến hành" },
    ],
  },
  {
    id: "n5-kuru",
    character: "来",
    hanViet: "LAI",
    meaning: "Đến, tương lai",
    onyomi: ["ライ"],
    kunyomi: ["く.る", "きた.る"],
    strokeCount: 7,
    jlpt: "N5",
    radical: "木",
    radicalName: "Bộ Mộc",
    examples: [
      { word: "来る", reading: "くる (Kuru)", meaning: "Đến" },
      { word: "来週", reading: "らいしゅう (Raishuu)", meaning: "Tuần sau" },
      { word: "来年", reading: "らいねん (Rainen)", meaning: "Năm sau" },
      { word: "未来", reading: "みらい (Mirai)", meaning: "Tương lai" },
    ],
  },
  {
    id: "n5-kaeru",
    character: "帰",
    hanViet: "QUY",
    meaning: "Trở về, hồi quy",
    onyomi: ["キ"],
    kunyomi: ["かえ.る", "かえ.す"],
    strokeCount: 10,
    jlpt: "N5",
    radical: "巾",
    radicalName: "Bộ Cân",
    examples: [
      { word: "帰る", reading: "かえる (Kaeru)", meaning: "Trở về" },
      { word: "帰国", reading: "きこく (Kikoku)", meaning: "Về nước" },
      { word: "日帰り", reading: "ひがえり (Higaeri)", meaning: "Đi về trong ngày" },
    ],
  },
  {
    id: "n5-yasumu",
    character: "休",
    hanViet: "HƯU",
    meaning: "Nghỉ ngơi, hưu trí",
    onyomi: ["キュウ"],
    kunyomi: ["やす.む", "やす.まる"],
    strokeCount: 6,
    jlpt: "N5",
    radical: "人",
    radicalName: "Bộ Nhân",
    examples: [
      { word: "休む", reading: "やすむ (Yasumu)", meaning: "Nghỉ ngơi" },
      { word: "休み", reading: "やすみ (Yasumi)", meaning: "Kỳ nghỉ" },
      { word: "休日", reading: "きゅうじつ (Kyuujitsu)", meaning: "Ngày nghỉ" },
      { word: "夏休み", reading: "なつやすみ (Natsuyasumi)", meaning: "Nghỉ hè" },
    ],
  },
  {
    id: "n5-tomodachi",
    character: "友",
    hanViet: "HỮU",
    meaning: "Bạn bè, bằng hữu",
    onyomi: ["ユウ"],
    kunyomi: ["とも"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "又",
    radicalName: "Bộ Hựu",
    examples: [
      { word: "友達", reading: "ともだち (Tomodachi)", meaning: "Bạn bè" },
      { word: "友人", reading: "ゆうじん (Yuujin)", meaning: "Bạn thân" },
      { word: "親友", reading: "しんゆう (Shin'yuu)", meaning: "Bạn tri kỷ" },
    ],
  },
  {
    id: "n5-kuruma",
    character: "車",
    hanViet: "XA",
    meaning: "Xe cộ",
    onyomi: ["シャ"],
    kunyomi: ["くるま"],
    strokeCount: 7,
    jlpt: "N5",
    radical: "車",
    radicalName: "Bộ Xa",
    examples: [
      { word: "車", reading: "くるま (Kuruma)", meaning: "Ô tô, xe" },
      { word: "電車", reading: "でんしゃ (Densha)", meaning: "Tàu điện" },
      { word: "自転車", reading: "じてんしゃ (Jitensha)", meaning: "Xe đạp" },
      { word: "自動車", reading: "じどうしゃ (Jidousha)", meaning: "Xe hơi" },
    ],
  },
  {
    id: "n5-den",
    character: "電",
    hanViet: "ĐIỆN",
    meaning: "Điện lực, sấm sét",
    onyomi: ["デン"],
    kunyomi: [],
    strokeCount: 13,
    jlpt: "N5",
    radical: "雨",
    radicalName: "Bộ Vũ",
    examples: [
      { word: "電気", reading: "でんき (Denki)", meaning: "Điện, đèn điện" },
      { word: "電話", reading: "でんわ (Denwa)", meaning: "Điện thoại" },
      { word: "電車", reading: "でんしゃ (Densha)", meaning: "Tàu điện" },
    ],
  },
  {
    id: "n5-ki_spirit",
    character: "気",
    hanViet: "KHÍ",
    meaning: "Khí chất, tinh thần, thời tiết",
    onyomi: ["キ", "ケ"],
    kunyomi: ["いき"],
    strokeCount: 6,
    jlpt: "N5",
    radical: "气",
    radicalName: "Bộ Khí",
    examples: [
      { word: "天気", reading: "てんき (Tenki)", meaning: "Thời tiết" },
      { word: "元気", reading: "げんき (Genki)", meaning: "Khỏe mạnh" },
      { word: "気持ち", reading: "きもち (Kimochi)", meaning: "Cảm giác, tâm trạng" },
      { word: "気をつける", reading: "きをつける (Ki o tsukeru)", meaning: "Cẩn thận" },
    ],
  },
  {
    id: "n5-ten",
    character: "天",
    hanViet: "THIÊN",
    meaning: "Trời, thiên đường",
    onyomi: ["テン"],
    kunyomi: ["あまつ", "あめ"],
    strokeCount: 4,
    jlpt: "N5",
    radical: "大",
    radicalName: "Bộ Đại",
    examples: [
      { word: "天気", reading: "てんき (Tenki)", meaning: "Thời tiết" },
      { word: "天国", reading: "てんごく (Tengoku)", meaning: "Thiên đường" },
      { word: "天才", reading: "てんさい (Tensai)", meaning: "Thiên tài" },
    ],
  },
  {
    id: "n5-ame",
    character: "雨",
    hanViet: "VŨ",
    meaning: "Mưa",
    onyomi: ["ウ"],
    kunyomi: ["あめ", "あま-"],
    strokeCount: 8,
    jlpt: "N5",
    radical: "雨",
    radicalName: "Bộ Vũ",
    examples: [
      { word: "雨", reading: "あめ (Ame)", meaning: "Cơn mưa" },
      { word: "大雨", reading: "おおあめ (Ooame)", meaning: "Mưa to" },
      { word: "雨期", reading: "うき (Uki)", meaning: "Mùa mưa" },
    ],
  },

  // ─── JLPT N4 / N3 SAMPLES ────────────────────────────────────────────────
  {
    id: "n4-ai",
    character: "愛",
    hanViet: "ÁI",
    meaning: "Tình yêu, yêu thương",
    onyomi: ["アイ"],
    kunyomi: ["いと.しい", "まな"],
    strokeCount: 13,
    jlpt: "N4",
    radical: "心",
    radicalName: "Bộ Tâm",
    examples: [
      { word: "愛", reading: "あい (Ai)", meaning: "Tình yêu" },
      { word: "愛情", reading: "あいじょう (Aijou)", meaning: "Tình thương" },
      { word: "愛する", reading: "あいする (Aisuru)", meaning: "Yêu thương" },
    ],
  },
  {
    id: "n4-kokoro",
    character: "心",
    hanViet: "TÂM",
    meaning: "Trái tim, tâm trí",
    onyomi: ["シン"],
    kunyomi: ["こころ"],
    strokeCount: 4,
    jlpt: "N4",
    radical: "心",
    radicalName: "Bộ Tâm",
    examples: [
      { word: "心", reading: "こころ (Kokoro)", meaning: "Trái tim, tấm lòng" },
      { word: "安心", reading: "あんしん (Anshin)", meaning: "Yên tâm" },
      { word: "心配", reading: "しんぱい (Shinpai)", meaning: "Lo lắng" },
      { word: "中心", reading: "ちゅうしん (Chuushin)", meaning: "Trung tâm" },
    ],
  },
  {
    id: "n4-ie",
    character: "家",
    hanViet: "GIA",
    meaning: "Nhà cửa, gia đình, chuyên gia",
    onyomi: ["カ", "ケ"],
    kunyomi: ["いえ", "や", "うち"],
    strokeCount: 10,
    jlpt: "N4",
    radical: "宀",
    radicalName: "Bộ Miên",
    examples: [
      { word: "家", reading: "いえ (Ie)", meaning: "Ngôi nhà" },
      { word: "家族", reading: "かぞく (Kazoku)", meaning: "Gia đình" },
      { word: "画家", reading: "がか (Gaka)", meaning: "Họa sĩ" },
      { word: "家賃", reading: "やちん (Yachin)", meaning: "Tiền thuê nhà" },
    ],
  },
  {
    id: "n3-kan",
    character: "漢",
    hanViet: "HÁN",
    meaning: "Chữ Hán, người Hán",
    onyomi: ["カン"],
    kunyomi: [],
    strokeCount: 13,
    jlpt: "N3",
    radical: "水",
    radicalName: "Bộ Thủy",
    examples: [
      { word: "漢字", reading: "かんじ (Kanji)", meaning: "Chữ Hán" },
      { word: "漢方", reading: "かんぽう (Kanpou)", meaning: "Đông y, thuốc Bắc" },
    ],
  },
  {
    id: "n3-ji",
    character: "字",
    hanViet: "TỰ",
    meaning: "Chữ viết, ký tự",
    onyomi: ["ジ"],
    kunyomi: ["あざ", "あざな"],
    strokeCount: 6,
    jlpt: "N3",
    radical: "子",
    radicalName: "Bộ Tử",
    examples: [
      { word: "漢字", reading: "かんじ (Kanji)", meaning: "Chữ Hán" },
      { word: "文字", reading: "もじ (Moji)", meaning: "Ký tự, chữ viết" },
      { word: "数字", reading: "すうじ (Suuji)", meaning: "Chữ số" },
    ],
  },
  {
    id: "n3-michi",
    character: "道",
    hanViet: "ĐẠO",
    meaning: "Con đường, đạo lý, phương pháp",
    onyomi: ["ドウ", "トウ"],
    kunyomi: ["みち"],
    strokeCount: 12,
    jlpt: "N3",
    radical: "辶",
    radicalName: "Bộ Xước",
    examples: [
      { word: "道", reading: "みち (Michi)", meaning: "Con đường" },
      { word: "茶道", reading: "さどう (Sadou)", meaning: "Trà đạo" },
      { word: "柔道", reading: "じゅうどう (Juudou)", meaning: "Judo" },
      { word: "道具", reading: "どうぐ (Dougu)", meaning: "Dụng cụ" },
    ],
  },
  {
    id: "n2-yume",
    character: "夢",
    hanViet: "MỘNG",
    meaning: "Giấc mơ, ước mơ",
    onyomi: ["ム", "ボウ"],
    kunyomi: ["ゆめ", "ゆめ.みる"],
    strokeCount: 13,
    jlpt: "N2",
    radical: "夕",
    radicalName: "Bộ Tịch",
    examples: [
      { word: "夢", reading: "ゆめ (Yume)", meaning: "Giấc mơ" },
      { word: "夢中", reading: "むちゅう (Muchuu)", meaning: "Say mê, đắm chìm" },
      { word: "悪夢", reading: "あくむ (Akumu)", meaning: "Cơn ác mộng" },
    ],
  },
  {
    id: "n1-hibiki",
    character: "響",
    hanViet: "HƯỞNG",
    meaning: "Âm hưởng, ảnh hưởng, vang vọng",
    onyomi: ["キョウ"],
    kunyomi: ["ひび.く"],
    strokeCount: 20,
    jlpt: "N1",
    radical: "音",
    radicalName: "Bộ Âm",
    examples: [
      { word: "影響", reading: "えいきょう (Eikyou)", meaning: "Ảnh hưởng" },
      { word: "響く", reading: "ひびく (Hibiku)", meaning: "Vang vọng" },
      { word: "交響曲", reading: "こうきょうきょく (Koukyoukyoku)", meaning: "Bản giao hưởng" },
    ],
  },
];
